### ISSUE TITLE
Cannot link against opus in Arch linux

### ISSUE THREAD

**Issue by yuvadm** [mempko/firestr#13]
I'm packaging firestr for Arch (on the AUR) and despite having libopus 1.1 installed I'm getting:
```
/usr/bin/ld: cannot find -lopus
```

Is it expecting some other version, or something?

**Comment by mempko** [comment]
I believe I try to statically link against libopus. Looks like Arch only has the dynamic library. You can try downloading libopus source and compiling a static library. 

Another alternative is change the CMakeLists.txt to link against the dynamic library on line 92.

**Comment by yuvadm** [comment]
Same error for botan and snappy. Why are you statically linking? Pretty much every single distro uses dynlibs.

**Comment by mempko** [comment]
Ha, yes obviously those other ones would have problems. I updated the build script to use dynamic libraries for all dependencies on linux. Please try again.

The reason I used static is because in the beginning, I was passing the binary around to people without packaging it. I just never switched back to dynamic linking. It should be fixed now.

**Comment by yuvadm** [comment]
Perfect, solved!
